-- create_livesupport_user.sql
-- DEPRECATED: database creation is now managed by Prisma/PostgreSQL.
--
-- The current app uses Prisma ORM with PostgreSQL, so schema creation is
-- handled through Prisma migrations or `prisma db push`.
--
-- To initialize the database schema, first ensure your PostgreSQL database
-- exists and DATABASE_URL is configured correctly, then run:
--
--   npx prisma db push
--   npx prisma generate
--
-- This file is retained for history only and should not be used for
-- runtime initialization in the current Prisma/Postgres architecture.
