import { createHash } from 'node:crypto';

/**
 * Order State Management Utilities
 * Ensures strict compliance with STRICT AI ORDER CREATION AND CONFIRMATION SYSTEM
 * 
 * CRITICAL: These functions enforce that:
 * 1. Order IDs ONLY come from database
 * 2. Draft orders are cleared after creation
 * 3. Conversation state is updated after order creation
 * 4. Old Order IDs are NEVER reused or displayed
 * 5. Orders are never confirmed without database creation
 */

/**
 * Creates a structured order confirmation object that enforces data origin
 * MUST be built ONLY from the newly created database order
 * 
 * @param {Object} createdOrder - The order returned from database after creation
 * @param {Array} lineItems - Line items from the resolved menu
 * @param {Object} pricing - Pricing calculation result
 * @returns {Object} Structured confirmation that only contains database-sourced data
 * 
 * VIOLATION PREVENTION:
 * - orderId MUST come from createdOrder.id or createdOrder.order_id
 * - pricing MUST come from pricing object, not from customer input
 * - Status MUST be from createdOrder.status, not assumed
 */
export function createStructuredOrderConfirmation(createdOrder = {}, lineItems = [], pricing = {}) {
  // STRICT VALIDATION: Order ID must exist and come from database
  if (!createdOrder || !String(createdOrder.order_id || '').trim()) {
    throw new Error('CRITICAL: Cannot create confirmation without valid database-generated Order ID. Database order creation may have failed.');
  }

  const orderId = String(createdOrder.order_id || '').trim();
  
  // STRICT VALIDATION: Verify order has confirmed status
  if (String(createdOrder.status || '').toLowerCase() !== 'confirmed') {
    throw new Error(`CRITICAL: Order ${orderId} has status "${createdOrder.status}", not "confirmed". Cannot confirm order with invalid status.`);
  }

  // STRICT VALIDATION: Ensure we have valid pricing
  if (!pricing || typeof pricing.finalTotal !== 'number') {
    throw new Error(`CRITICAL: Invalid pricing for order ${orderId}. Pricing must include finalTotal.`);
  }

  // STRICT VALIDATION: Ensure line items are present
  if (!Array.isArray(lineItems) || lineItems.length === 0) {
    throw new Error(`CRITICAL: Order ${orderId} has no line items. Cannot create confirmation without items.`);
  }

  return {
    type: 'ORDER_CONFIRMATION',
    orderCreated: true,
    orderId,
    customerId: createdOrder.customer_name || createdOrder.customerName || 'Customer',
    items: lineItems.map(item => ({
      name: item.name,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      total: item.lineTotal
    })),
    subtotal: Number(pricing.subtotal || 0),
    tax: Number(pricing.tax || 0),
    deliveryFee: Number(pricing.deliveryFee || 0),
    discounts: Number(pricing.discountAmount || 0),
    grandTotal: Number(pricing.finalTotal || 0),
    estimatedPreparationTime: createdOrder.estimatedPreparationTime || 25,
    estimatedDeliveryTime: createdOrder.estimatedDeliveryTime || 40,
    status: 'Confirmed',
    timestamp: new Date().toISOString(),
    // Track the source of truth
    databaseValidation: {
      orderId: String(createdOrder.order_id || ''),
      status: String(createdOrder.status || ''),
      createdAt: createdOrder.order_date || createdOrder.created_at || new Date().toISOString()
    }
  };
}

/**
 * Validates that a structured confirmation ONLY contains database-sourced data
 * 
 * @param {Object} confirmation - The structured confirmation to validate
 * @returns {boolean} True if valid, throws error otherwise
 * 
 * VIOLATION PREVENTION:
 * - Ensures orderId came from database (not generated by AI)
 * - Ensures status is exactly "Confirmed"
 * - Ensures all pricing came from database calculations
 */
export function validateStructuredConfirmation(confirmation = {}) {
  if (confirmation.type !== 'ORDER_CONFIRMATION') {
    throw new Error('Invalid confirmation type: not an ORDER_CONFIRMATION');
  }

  if (confirmation.orderCreated !== true) {
    throw new Error('Invalid confirmation: orderCreated is not true');
  }

  if (!String(confirmation.orderId || '').trim()) {
    throw new Error('CRITICAL: Confirmation missing Order ID');
  }

  if (confirmation.status !== 'Confirmed') {
    throw new Error(`CRITICAL: Confirmation status is "${confirmation.status}", not "Confirmed"`);
  }

  if (!confirmation.databaseValidation || !confirmation.databaseValidation.orderId) {
    throw new Error('CRITICAL: Confirmation missing database validation proof');
  }

  return true;
}

/**
 * Creates a clean draft order state (zeros out the previous order)
 * Must be called AFTER order is successfully created
 * 
 * VIOLATION PREVENTION:
 * - Clears orderId so it can't leak into next order
 * - Clears items from previous order
 * - Clears total so it can't be reused
 * - Resets status to null
 * 
 * @returns {Object} Fresh draft order with all previous data cleared
 */
export function createClearedDraftOrder() {
  const now = new Date().toISOString();
  return {
    items: [],
    quantities: {},
    modifiers: {},
    allergies: [],
    delivery: null,
    pickup: null,
    tableNumber: null,
    address: null,
    paymentMethod: null,
    discounts: [],
    notes: '',
    orderId: null,           // ← CRITICAL: Must be null
    total: null,             // ← CRITICAL: Must be null
    status: null,            // ← CRITICAL: Must be null
    createdAt: now,
    updatedAt: now
  };
}

/**
 * Validates a created order record before displaying confirmation
 * 
 * VIOLATION PREVENTION:
 * - Ensures orderId exists and is non-empty
 * - Ensures status is confirmed
 * - Ensures order came from database (not fabricated)
 * - Ensures required fields are present
 * 
 * @param {Object} order - Order record from database
 * @returns {Object} { valid: boolean, error?: string }
 */
export function validateCreatedOrderRecord(order = {}) {
  if (!order) {
    return { valid: false, error: 'Order record is null or undefined' };
  }

  // CRITICAL: Order ID must exist
  const orderId = String(order.order_id || order.id || '').trim();
  if (!orderId) {
    return { valid: false, error: 'CRITICAL: Order created without Order ID from database' };
  }

  // CRITICAL: Status must be confirmed
  const status = String(order.status || '').toLowerCase();
  if (status !== 'confirmed') {
    return { valid: false, error: `CRITICAL: Order ${orderId} has status "${status}", not "confirmed"` };
  }

  // CRITICAL: Customer name must exist
  if (!order.customer_name && !order.customerName) {
    return { valid: false, error: `CRITICAL: Order ${orderId} missing customer name` };
  }

  // CRITICAL: Amount must be a valid number
  const totalAmount = Number(order.total_amount || order.finalTotal || order.amount || 0);
  if (totalAmount <= 0) {
    return { valid: false, error: `CRITICAL: Order ${orderId} has invalid amount: ${totalAmount}` };
  }

  // CRITICAL: Must have order date
  if (!order.order_date && !order.created_at) {
    return { valid: false, error: `CRITICAL: Order ${orderId} missing order_date from database` };
  }

  return { valid: true };
}

/**
 * Generates an idempotency key for an order creation request
 * Prevents duplicate orders if request is retried
 * 
 * @param {Object} params - Order creation parameters
 * @returns {string} Idempotency key
 */
export function generateOrderIdempotencyKey(params = {}) {
  const { conversationId, phone, customerName, items = [] } = params;
  
  // Build a deterministic key from order content
  const itemsHash = items
    .map(item => `${item.name}:${item.quantity}`)
    .sort()
    .join('|');
  
  const keyParts = [
    conversationId,
    phone,
    customerName,
    itemsHash
  ].filter(Boolean);

  // Create a hash from the key parts
  return createHash('sha256')
    .update(keyParts.join('::'))
    .digest('hex')
    .substring(0, 16);
}

/**
 * Checks if an order with the same idempotency key already exists
 * Used to prevent duplicate order creation
 * 
 * @param {string} idempotencyKey - The idempotency key
 * @param {Function} dbQuery - Database query function
 * @returns {Promise<Object|null>} Existing order if found, null otherwise
 */
export async function findExistingOrderByIdempotencyKey(idempotencyKey, dbQuery) {
  return new Promise((resolve) => {
    dbQuery(
      'SELECT id, order_id, status FROM orders WHERE idempotency_key = ? LIMIT 1',
      [idempotencyKey],
      (err, rows) => {
        if (err || !rows || rows.length === 0) {
          resolve(null);
        } else {
          resolve(rows[0]);
        }
      }
    );
  });
}

/**
 * Creates next conversation session state after order is confirmed
 * CRITICAL: Clears draft order to prevent reuse
 * 
 * @param {Object} currentSession - Current conversation session
 * @param {Object} createdOrder - Order just created from database
 * @returns {Object} New session state with cleared draft order
 */
export function createPostOrderConversationState(currentSession = {}, createdOrder = {}) {
  const orderId = String(createdOrder.order_id || '').trim();
  
  if (!orderId) {
    throw new Error('Cannot create post-order state without valid Order ID from database');
  }

  return {
    ...currentSession,
    workflowState: 'Order Created',
    pendingQuestions: [],
    draftOrder: createClearedDraftOrder(),
    history: [
      ...(Array.isArray(currentSession.history) ? currentSession.history : []),
      {
        role: 'system',
        message: `Order ${orderId} successfully created and confirmed`,
        timestamp: new Date().toISOString()
      }
    ],
    lastOrderId: orderId,  // Track the last order created
    lastOrderCreatedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
}

/**
 * Prevents returning cached Order IDs in subsequent requests
 * CRITICAL: Ensures new orders get new IDs
 * 
 * @param {Object} conversationState - Current conversation state
 * @param {string} newOrderId - The Order ID from the LATEST order creation
 * @returns {boolean} True if we should proceed with new order, false if using stale state
 */
export function shouldClearCachedOrderId(conversationState = {}, newOrderId = '') {
  // If conversation state has an orderId but it's different from the new one,
  // the old one is stale and should not be returned
  if (conversationState?.draftOrder?.orderId && conversationState.draftOrder.orderId !== newOrderId) {
    return true; // Clear it
  }
  
  return false;
}

/**
 * Ensures conversation state is never reused across different orders
 * Validates that order state matches current database state
 * 
 * @param {Object} conversationState - State to validate
 * @param {string} expectedOrderId - The Order ID we expect (from current order creation)
 * @returns {Object} { valid: boolean, reason?: string }
 */
export function validateOrderStateIntegrity(conversationState = {}, expectedOrderId = '') {
  if (!expectedOrderId) {
    return { valid: false, reason: 'No expected Order ID provided for validation' };
  }

  const stateOrderId = conversationState?.draftOrder?.orderId;
  
  // If state has an order ID and it's different from what we just created,
  // it's stale and should not be used
  if (stateOrderId && stateOrderId !== expectedOrderId) {
    return { 
      valid: false, 
      reason: `State has stale Order ID ${stateOrderId}, expected ${expectedOrderId}` 
    };
  }

  return { valid: true };
}

export default {
  createStructuredOrderConfirmation,
  validateStructuredConfirmation,
  createClearedDraftOrder,
  validateCreatedOrderRecord,
  generateOrderIdempotencyKey,
  findExistingOrderByIdempotencyKey,
  createPostOrderConversationState,
  shouldClearCachedOrderId,
  validateOrderStateIntegrity
};
